steps:
  # Build and push container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_STAGING_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CONTAINER_NAME}:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile.simple'
      - '.'
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_STAGING_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CONTAINER_NAME}:${SHORT_SHA}'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_CONTAINER_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_STAGING_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_NAME}/${_CONTAINER_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300s'
    id: 'deploy-cloudrun'

  # Test deployment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '--fail'
      - '--silent'
      - '--show-error'
      - '--location'
      - '--max-time'
      - '30'
      - 'https://${_CONTAINER_NAME}-[RANDOM_HASH]-${_REGION}.a.run.app/health'
    id: 'test-deployment'
    waitFor: ['deploy-cloudrun']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _STAGING_PROJECT_ID: 'qwiklabs-gcp-02-bd7da31f7909'
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY_REPO_NAME: 'contentcortex-agent-repo'
  _CONTAINER_NAME: 'contentcortex-agent'

timeout: '1200s'